// Κεντρικές σταθερές για όλα τα routes της εφαρμογής.
// Χρησιμοποίησέ τες σε κάθε router.push/replace αντί για strings,
// ώστε μια μελλοντική μετονομασία αρχείου να χρειάζεται αλλαγή σε ΕΝΑ σημείο.
export const ROUTES = {
  // Κοινή οθόνη: την ανοίγουν και ο γιατρός και ο ασθενής.
  RECORD_DETAIL: '/record_detail',
  LOGIN: '/login',
  PATIENT_LOGIN: '/patient/patient_login',
  PATIENT_REGISTER: '/patient/patient_register',
  PATIENT_ACCESS: '/patient/screens/patient_access',
  PATIENT_ADD_ACCESS: '/patient/screens/patient_add_access',
  PATIENT_HOME: '/patient/screens/patient_home',
  // Τα στοιχεία του χρήστη και οι ενέργειες λογαριασμού σε μία οθόνη - ήταν χωρισμένα
  // σε "Προφίλ" και "Ρυθμίσεις", που όμως δεν είχαν ποτέ καμία ρύθμιση μέσα τους.
  PATIENT_ACCOUNT: '/patient/screens/patient_account',
  PATIENT_HOSPITALIZATIONS: '/patient/istoriko/patient_hospitalizations',
  PATIENT_VACCINATIONS: '/patient/istoriko/patient_vaccinations',
  PATIENT_ALLERGIES: '/patient/istoriko/patient_allergies',
  PATIENT_DIAGNOSEIS: '/patient/istoriko/patient_diagnoseis',
  PATIENT_MEDICATIONS: '/patient/istoriko/patient_medications',
  PATIENT_EXAMS: '/patient/istoriko/patient_exams',
  DOCTOR_LOGIN: '/doctor/doctor_login',
  DOCTOR_REGISTER: '/doctor/doctor_register',
  DOCTOR_HOME: '/doctor/screens/doctor_home',
  DOCTOR_ADD_ACCESS: '/doctor/screens/doctor_add_access',
  DOCTOR_ACCOUNT: '/doctor/screens/doctor_account',
  DOCTOR_MED_HISTORY: '/doctor/patient_screens/med_history',
  DOCTOR_DIAGNOSEIS: '/doctor/patient_screens/doctor_diagnoseis',
  DIAGNOSIS_FORM: '/forms/diagnosis_form',
  DOCTOR_VACCINATIONS: '/doctor/patient_screens/doctor_vaccinations',
  VACCINATION_FORM: '/forms/vaccination_form',
  DOCTOR_ALLERGIES: '/doctor/patient_screens/doctor_allergies',
  ALLERGY_FORM: '/forms/allergy_form',
  DOCTOR_HOSPITALIZATIONS: '/doctor/patient_screens/doctor_hospitalizations',
  HOSPITALIZATION_FORM: '/forms/hospitalization_form',
  DOCTOR_MEDICATIONS: '/doctor/patient_screens/doctor_medications',
  MEDICATION_FORM: '/forms/medication_form',
  DOCTOR_EXAMS: '/doctor/patient_screens/doctor_exams',
  EXAM_FORM: '/forms/exam_form',
} as const;
