// Κεντρικές σταθερές για όλα τα routes της εφαρμογής.
// Χρησιμοποίησέ τες σε κάθε router.push/replace αντί για strings,
// ώστε μια μελλοντική μετονομασία αρχείου να χρειάζεται αλλαγή σε ΕΝΑ σημείο.
export const ROUTES = {
  // Κοινή οθόνη: την ανοίγουν και ο γιατρός και ο ασθενής.
  RECORD_DETAIL: '/record_detail',
  LOGIN: '/login',
  PATIENT_LOGIN: '/patient/patient_login',
  PATIENT_REGISTER: '/patient/patient_register',
  PATIENT_ACCESS: '/patient/screens/patient_access',
  PATIENT_HOME: '/patient/screens/patient_home',
  PATIENT_SETTINGS: '/patient/screens/patient_settings',
  PATIENT_PROFILE: '/patient/patient_profile',
  PATIENT_HOSPITALIZATIONS: '/patient/istoriko/patient_hospitalizations',
  PATIENT_VACCINATIONS: '/patient/istoriko/patient_vaccinations',
  PATIENT_ALLERGIES: '/patient/istoriko/patient_allergies',
  PATIENT_DIAGNOSEIS: '/patient/istoriko/patient_diagnoseis',
  PATIENT_MEDICATIONS: '/patient/istoriko/patient_medications',
  PATIENT_EXAMS: '/patient/istoriko/patient_exams',
  DOCTOR_LOGIN: '/doctor/doctor_login',
  DOCTOR_REGISTER: '/doctor/doctor_register',
  DOCTOR_PROFILE: '/doctor/doctor_profile',
  DOCTOR_HOME: '/doctor/screens/doctor_home',
  DOCTOR_SETTINGS: '/doctor/screens/doctor_settings',
  DOCTOR_MED_HISTORY: '/doctor/patient_screens/med_history',
  DOCTOR_DIAGNOSEIS: '/doctor/patient_screens/doctor_diagnoseis',
  DOCTOR_DIAGNOSIS_FORM: '/doctor/patient_screens/doctor_diagnosis_form',
  DOCTOR_VACCINATIONS: '/doctor/patient_screens/doctor_vaccinations',
  DOCTOR_VACCINATION_FORM: '/doctor/patient_screens/doctor_vaccination_form',
  DOCTOR_ALLERGIES: '/doctor/patient_screens/doctor_allergies',
  DOCTOR_ALLERGY_FORM: '/doctor/patient_screens/doctor_allergy_form',
  DOCTOR_HOSPITALIZATIONS: '/doctor/patient_screens/doctor_hospitalizations',
  DOCTOR_HOSPITALIZATION_FORM: '/doctor/patient_screens/doctor_hospitalization_form',
  DOCTOR_MEDICATIONS: '/doctor/patient_screens/doctor_medications',
  DOCTOR_MEDICATION_FORM: '/doctor/patient_screens/doctor_medication_form',
  DOCTOR_EXAMS: '/doctor/patient_screens/doctor_exams',
  DOCTOR_EXAM_FORM: '/doctor/patient_screens/doctor_exam_form',
} as const;
